on:
  push:
  schedule:
    - cron: '30 2 * * 0'
name: build
jobs:
  deps:
    runs-on: ubuntu-latest

    name: Check for new versions of dependencies
    steps:
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10'

      - name: Install packdeps
        run: cabal install packdeps

      - uses: actions/checkout@v2

      - name: Run packdeps
        run: |
          cabal_files="$(find . -name '*.cabal')"
          failed=0
          while read cabal_file; do
            "$HOME/.cabal/bin/packdeps" "$cabal_file" || failed=1
          done <<EOF
          $cabal_files
          EOF
          [ $failed -eq 0 ] || exit 1

  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.10', '9.0']
        os: [ubuntu-latest, macOS-latest]

    name: Build Package
    steps:
      - name: Install Ubuntu system dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo -s apt-get update
          sudo -s apt-get install --yes libcairo2-dev libgtk-3-dev libpango1.0-dev

      - name: Install macOS system dependencies
        if: matrix.os == 'macOS-latest'
        run: brew install cairo gtk+3 pango

      - uses: actions/checkout@v2

      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Build libraries
        run: cabal build all

      - name: Check if Quartz support was compiled
        if: matrix.os == 'macOS-latest'
        run: |
          cat >Test.hs <<EOF
          module Main where
          import Graphics.Rendering.Cairo
          main = withQuartzSurfaceForCGContext undefined 100 100 (const $ putStrLn "OK")
          EOF
          cabal exec ghc -- -o test Test.hs
